// src/components/pages/teleop/Teleop.tsx
import {
  TeleopGrid,
  TopGrid,
  BottomGrid,
} from '@/components/pages/teleop/Teleop.styles'
import { Map2D } from '@/components'
import Camera from '@/components/ros/Camera'
import { cameraModule, teleopModule } from '@/store'
import { createComponent, state } from 'vue-function-api'
import Dashboard from '@/components/pages/teleop/dashboard/Dashboard'

const Teleop = createComponent({
  setup() {
    const bottomCamera = state(
      cameraModule.getCamera(teleopModule.bottomCamera)
    )
    const leftCamera = state(cameraModule.getCamera(teleopModule.leftCamera))
    const rightCamera = state(cameraModule.getCamera(teleopModule.rightCamera))

    return (
      <TeleopGrid>
        <TopGrid>
          <Camera type={leftCamera.type} topic={leftCamera.topic} />
          <Camera type={rightCamera.type} topic={rightCamera.topic} />
        </TopGrid>
        <BottomGrid>
          <Dashboard />
          <Map2D />
          <Camera type={bottomCamera.type} topic={bottomCamera.topic} />
        </BottomGrid>
      </TeleopGrid>
    )
  },
})

export default Teleop

// src/components/tabs/Teleop.vue
<template>
  <div class="teleop">
    <div class="cameras">
      <camera :type="leftCamera.type" :topic="leftCamera.topic" />
      <camera :type="rightCamera.type" :topic="rightCamera.topic" />
    </div>
    <div class="bottom-panel">
      <dashboard />
      <Map2D />
      <camera :type="bottomCamera.type" :topic="bottomCamera.topic" />
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { Camera, Map2D } from '@/components'
import Viewer3D from '@/components/ros/Viewer3D.vue'
import { cameraModule, teleopModule } from '@/store'
import Dashboard from '../pages/teleop/dashboard/Dashboard'

@Component({ components: { Camera, Dashboard, Map2D } })
export default class Teleop extends Vue {
  get leftCamera() {
    return cameraModule.getCamera(teleopModule.leftCamera)
  }

  get rightCamera() {
    return cameraModule.getCamera(teleopModule.rightCamera)
  }

  get bottomCamera() {
    return cameraModule.getCamera(teleopModule.bottomCamera)
  }
}
</script>

<style lang="scss">
.teleop {
  height: 100%;
  display: grid;
  align-content: stretch;
  grid-template-rows: 70% 30%;

  .cameras {
    display: grid;
    grid-template-columns: 1fr 1fr;

    > div {
      box-shadow: inset 0 0 0 0.5px #000000;
    }
  }

  .bottom-panel {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;

    > div {
      box-shadow: inset 0 0 0 0.5px #000000;
    }
  }
}
</style>
